### PR TITLE
Add helm chart

### PR DESCRIPTION
**Pull request by TheChef23**
I created a Helm chart in the following repository: https://github.com/cyso/helm-smokeping-prober

I figured it might be better to contribute it to the source project. If you want to @SuperQ, then go ahead and merge it into this project, i'll then either archive or delete the other repository.

### CODE REVIEW

**Comment by SuperQ** [comment]
Maybe this would be a better fit for https://github.com/prometheus-community/helm-charts? This way all of the automated testing tooling is available.

**Comment by TheChef23** [comment]
Thanks for the suggestion. I have never contributed there before, but i'll see if I'm able to meet the requirements. I'll have to change some stuff with regards to versioning I think. Are there any other things you would think need attention before it could more merged?

**Comment by SuperQ** [comment]
I'm not totally up on the standards used in that repo. But it's a nice collection, which makes it easier for people to find this.

**Comment by TheChef23** [comment]
I'll give it a shot! Go ahead and close this request. Thanks!

**Pull request closed without merging**
