### PR TITLE
Migrate logging to github.com/go-kit/log

### PR DESCRIPTION
**Pull request by dswarbrick**
prometheus/common/log no longer provides a wrapper for logrus, and most
of the Prometheus ecosystem is migrating to go-kit for logging.

Signed-off-by: Daniel Swarbrick <daniel.swarbrick@gmail.com>

### CODE REVIEW

**Comment by dswarbrick** [comment]
@SuperQ Please review this when you get a moment. The prometheus-smokeping-prober package in Debian is currently FTBFS since it depends on the deprecated logrus wrapper in older versions of prometheus/common.

This PR does nothing more than replace the existing logging with go-kit. I would really appreciate if you could tag a new release once this is merged, so that we can update the Debian package and get it buildable again before the Ubuntu jammy freeze.

**Review by SuperQ — APPROVED** [review]
Nice, thanks!

**Comment by dswarbrick** [comment]
Incidentally, I also just discovered that go-kit/log only respects the `--log.level` flag from promlog.Config if you build with prometheus/common 0.26 or later. You might want to freshen up some of the versions in go.mod.

**Comment by SuperQ** [comment]
Sure, I'll freshen up the dependencies.

**Pull request merged**
