### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by SuperQ**
Turn off the RTT recorder to avoid leaking memory.

Fixes: https://github.com/SuperQ/smokeping_prober/issues/42

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by towolf** [comment]
@superQ, are you sure this is fixed?

image

**Comment by SuperQ** [comment]
It should be, what metric is that, what version?

Can you pull a [pprof memory profile](https://www.freecodecamp.org/news/how-i-investigated-memory-leaks-in-go-using-pprof-on-a-large-codebase-4bec4325e192/)?

**Comment by towolf** [comment]
I will look into giving you more information next week. If you have easy instructions on what would be helpful here, that would be appreciated.

**Comment by towolf** [comment]
@SuperQ this is the metric `container_memory_working_set_bytes` for the smokeping_prober version `quay.io/superq/smokeping-prober-linux-amd64:v0.6.0`.

It got killed after little more than 48 hours, pinging about 15 Targets:

```
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 01 Jun 2022 11:26:48 +0200
      Finished:     Fri, 03 Jun 2022 12:06:08 +0200
    Restart Count:  1
    Limits:
      memory:  64Mi
```
I will look into giving you more information next week. If you have easy instructions on how do get the needed information in the running container running in Kubernetes, that would be appreciated.

**Pull request merged**
